### ISSUE TITLE
建议增加记忆窗口位置/调整窗口大小的设计

### ISSUE THREAD

**Issue by izwb003** [Styunlen/ReminderOfNEMT#1]
如题，建议在关闭时记忆上一次关闭时窗口所在的位置，下一次在该位置打开，因为这种东西一般都是放在屏幕角落处吧。。。
另希望时间设置能实时生效而不是需要重启软件。
另另希望可以不在任务栏显示图标并始终置顶。

---

（同2021高考生。。。高考加油~）

**Comment by Styunlen** [comment]
保存窗口位置功能已经有了哦，不过得使用菜单栏里的关闭按钮才可保存关闭位置，下一个版本可能会改，还有就是很抱歉最近一段时间因为高考首考的原因，可能没办法修改了。不过寒假的时候可能会对程序进行大改，添加一些更个性化的功能，以及自定义主题的功能。谢谢同届考生的祝福，也祝你旗开得胜，马到成功！

**Comment by izwb003** [comment]
> 
> 
> 保存窗口位置功能已经有了哦，不过得使用菜单栏里的关闭按钮才可保存关闭位置，下一个版本可能会改，还有就是很抱歉最近一段时间因为高考首考的原因，可能没办法修改了。不过寒假的时候可能会对程序进行大改，添加一些更个性化的功能，以及自定义主题的功能。谢谢同届考生的祝福，也祝你旗开得胜，马到成功！

好的，加油！
